package pageUIs;

import org.openqa.selenium.By;

public class MyAccountPageUI {
	public static final By MY_ACCOUNT_PAGE_FORM = By.xpath("//div[@class='page account-page customer-info-page']");
	public static final By GENDER_MALE_RADIOBUTTON = By.xpath("//span[@class='male']");
	public static final By GENDER_FEMALE_RADIOBUTTON = By.xpath("//span[@class='female']");
	public static final By FIRSTNAME_TEXTBOX = By.xpath("//input[@id='FirstName']");
	public static final By LASTNAME_TEXTBOX = By.xpath("//input[@id='LastName']");
	public static final By DATEOFBIRTH_DROPDOWN = By.xpath("//select[@name='DateOfBirthDay']");
	public static final By DATEOFMONTH_DROPDOWN = By.xpath("//select[@name='DateOfBirthMonth']");
	public static final By DATEOFYEAR_DROPDOWN = By.xpath("//select[@name='DateOfBirthYear']");
	public static final By EMAIL_TEXTBOX = By.xpath("//input[@id='Email']");
	public static final By COMPANYNAME_TEXTBOX = By.xpath("//input[@id='Company']");
	public static final By SAVE_BUTTON = By.xpath("//input[@id='save-info-button']");
	public static final By ADDRESS_LINKS = By.xpath("//a[@class='inactive'][contains(text(),'Addresses')]");
	public static final By ADDRESS_NEW_ADDRESS_BUTTON = By.xpath("//input[@class='button-1 add-address-button']");
	public static final By ADDRESS_NEW_ADDRESS_TABLE = By.xpath("//div[@class='edit-address']");
	public static final By ADDRESS_FIRSTNAME_TEXTBOX = By.xpath("//input[@id='Address_FirstName']");
	public static final By ADDRESS_LASTNAME_TEXTBOX = By.xpath("//input[@id='Address_LastName']");
	public static final By ADDRESS_EMAIL_TEXTBOX = By.xpath("//input[@id='Address_Email']");
	public static final By ADDRESS_COMPANYNAME_TEXTBOX = By.xpath("//input[@id='Address_Company']");
	public static final By ADDRESS_COUNTRY_DROPDOWN = By.xpath("//select[@id='Address_CountryId']");
	public static final By ADDRESS_STATE_DROPDOWN = By.xpath("//select[@id='Address_StateProvinceId']");
	public static final By ADDRESS_CITY_TEXTBOX = By.xpath("//input[@id='Address_City']");
	public static final By ADDRESS_ADDRESS01_TEXTBOX = By.xpath("//input[@id='Address_Address1']");
	public static final By ADDRESS_ADDRESS02_TEXTBOX = By.xpath("//input[@id='Address_Address2']");
	public static final By ADDRESS_ZIPCODE_TEXTBOX = By.xpath("//input[@id='Address_ZipPostalCode']");
	public static final By ADDRESS_PHONENUMBER_TEXTBOX = By.xpath("//input[@id='Address_PhoneNumber']");
	public static final By ADDRESS_FAXNUMBER_TEXTBOX = By.xpath("//input[@id='Address_FaxNumber']");
	public static final By ADDRESS_SAVE_BUTTON = By.xpath("//input[@class='button-1 save-address-button']");
	public static final By ADDRESS_INFO_TABLE = By.xpath("//ul[@class='info']");
	public static final By ADDRESS_FIRST_LAST_NAME_TEXT = By.xpath("//li[@class='name']");
	public static final By ADDRESS_EMAIL_TEXT = By.xpath("//li[@class='email']");
	public static final By ADDRESS_PHONENUMBER_TEXT = By.xpath("//li[@class='phone']");
	public static final By ADDRESS_FAXNUMBER_TEXT = By.xpath("//li[@class='fax']");
	public static final By ADDRESS_COMPANYNAME_TEXT = By.xpath("//li[@class='company']");
	public static final By ADDRESS_ADDRESS01_TEXT = By.xpath("//li[@class='address1']");
	public static final By ADDRESS_ADDRESS02_TEXT = By.xpath("//li[@class='address2']");
	public static final By ADDRESS_CITY_ZIPCODE_TEXT = By.xpath("//li[@class='city-state-zip']");
	public static final By ADDRESS_COUNTRY_TEXT = By.xpath("//li[@class='country']");
	public static final By CHANGE_PASSWORD_LINK = By.xpath("//a[contains(text(),'Change password')]");
	public static final By CHANGE_PASSWORD_FORM = By.xpath("//div[@class='page-body']//form");
	public static final By CHANGE_OLD_PASSWORD_TEXTBOX = By.xpath("//input[@id='OldPassword']");
	public static final By CHANGE_NEW_PASSWORD_TEXTBOX = By.xpath("//input[@id='NewPassword']");
	public static final By CHANGE_CONFIRM_NEW_PASSWORD_TEXTBOX = By.xpath("//input[@id='ConfirmNewPassword']");
	public static final By CHANGE_NEW_PASSWORD_BUTTON = By.xpath("//input[@class='button-1 change-password-button']");
	public static final By CHANGE_NEW_PASSWORD_RESULT_MESSAGE = By.xpath("//div[@class='result']");
	public static final By MY_PRODUCT_REVIEW_LINK = By.xpath("//a[contains(text(),'My product reviews')]");
	public static final By MY_PRODUCT_REVIEW_FORM = By.xpath("//div[@class='page account-page my-product-reviews-list-page']");
	public static final By MY_PRODUCT_REVIEW_PRODUCT_TITLE = By.xpath("//div[@class='review-item-head']");
	public static final By MY_PRODUCT_REVIEW_PRODUCT_DESCRIPTION = By.xpath("//div[@class='review-text']");
	public static final By MY_PRODUCT_REVIEW_PRODUCT_INFO = By.xpath("//div[@class='review-info']");
}
